# Generated by Django 3.1.2 on 2020-11-25 10:51

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_remove_group_description_html'),
        ('posts', '0002_remove_post_message_html'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('accounts', '0003_auto_20201125_1615'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default=accounts.models.get_default_profile_image, null=True, upload_to=accounts.models.get_profile_image_filepath),
        ),
    ]
