# Generated by Django 3.1.2 on 2020-11-02 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='description_html',
        ),
    ]
